import { Button, useMantineTheme } from '@mantine/core';
import { useViewportSize } from '@mantine/hooks';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { Navbar } from '../components/Navbar/Navbar';
import meImage from '../public/me.png';
import styles from '../styles/Home.module.css';
const Home: NextPage = () => {
  const theme = useMantineTheme();
  const { width } = useViewportSize();
  const [isMobile, setIsMobile] = useState(false);
  useEffect(() => {
    setIsMobile(width < 600 ? true : false);
  }, [width]);

  const goToLinkedIn = () => {
    window.open("https://www.linkedin.com/in/ben-hapip-07b014109/", '_blank');
  }
  return (
    <div className={styles.container}>

      <Head>
        <title>Ben Hapip's Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} style={{ color: theme.colors.ben[0] }}>
        <Navbar />
        <div className={styles.mainContainer}>
   

          <div className={styles.homeSection}>
            {isMobile && (
              <Image
                src={meImage}
                width="300"
                height="300"
                className={styles.meImage}
              />
            )}
            <div className={styles.aboutMe}>BEN HAPIP</div>
            <div
              className={styles.aboutMeSection}
              style={{ color: theme.colors.white[0] }}
            >
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industries standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book. It has
              survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged. It was
              popularised in the 1960s with the release of Letraset sheets
              containing Lorem Ipsum passages, and more recently with desktop
              publishing software like Aldus PageMaker including versions of
              Lorem Ipsum.
            </div>
            <div className={styles.buttonContainer}>
              <Button color="lightBen">VIEW MY THINGS</Button>
            </div>
          </div>
          {!isMobile && (
            <div onClick={()=> goToLinkedIn()}>
              <Image
                src={meImage}
                width="500"
                height="500"
                className={styles.meImage}
              />
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export default Home;
